## Numpy
- 파이썬에서 수학적 계산을 쉽게 할 수 있도록 도와주는 라이브러리

In [2]:
import numpy as np

In [3]:
# 1차원 배열 생성
array = np.array(["A", "B", "C", "D", "E"])
array

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [4]:
print(array.shape)   # 차원의 요소 개수
print(array.ndim)   # 차원
print(array.dtype)   # data type -> 공통적인 데이터 타입

(5,)
1
<U1


In [5]:
array2 = np.array([["A", "B", "C"], ["D", "E", "F"]])
array2

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype='<U1')

In [6]:
print(array2.shape)
print(array2.ndim)
print(array2.dtype)

(2, 3)
2
<U1


In [7]:
array3 = np.array([[["A", "B", "C"], ["D", "E", "F"]], [["A", "B", "C"], ["D", "E", "F"]]])
array3

array([[['A', 'B', 'C'],
        ['D', 'E', 'F']],

       [['A', 'B', 'C'],
        ['D', 'E', 'F']]], dtype='<U1')

In [8]:
print(array3.shape)
print(array3.ndim)
print(array3.dtype)

(2, 2, 3)
3
<U1


In [9]:
array4 = np.array([1, 2, 3, 4, 5])
print(array4.dtype)

# astype() - ndarray 타입변환
array4 = array4.astype(np.float64)
print(array4.dtype)

int32
float64


In [10]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[0:3]

array([1, 2, 3])

In [13]:
print(arr > 6)
print(arr[arr > 6])

[False False False False False False  True  True  True]
[7 8 9]


In [15]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

add = np.add(arr1, arr2)
print(add)

multiply = np.multiply(arr1, arr2)
print(multiply)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
